# Generated by Django 3.0.7 on 2020-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='ano_fundacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='editora',
            name='pais_origem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escritor',
            name='ano_nascimento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escritor',
            name='nacionalidade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
